### ISSUE TITLE
Thời gian sinh ticket không giống như  thời gian cài đặt trong tần suất của công việc

### ISSUE THREAD

**Issue by HueTranKieuAnh** [thanhhuyenle612/Planer#105]
Tại màn cài đặt tần suất của CVĐK:(lúc 17h ngày 24/12)
- Thời gian cấu hình: chạy việc 8h sáng hằng ngày, sinh ticket trước 1 giờ (ảnh)
![Image](https://github.com/user-attachments/assets/e1b3019e-6dc3-469c-9d97-39665d7589ef)

**Thực tế:**
- Sinh việc ngay sau khi tạo hoặc chỉnh sửa tần suất CVĐK (17h cùng ngày với lịch)
- Sinh kế hoạch và ticket cho cả các kế hoạch trong quá khứ
**Mong muốn:**
- Chỉ sinh việc lúc 7h sáng, và date_time_todo là 8h sáng
- Chỉ sinh lịch và ticket cho các kế hoạch trong tương lai, các kế hoạch trong quá khứ thì bỏ qua

**Comment by duclv66** [comment]
Thời gian cấu hình: chạy việc 8h sáng hằng ngày, sinh ticket trước 1 giờ
Thực tế:
Sinh việc ngay sau khi tạo (17h cùng ngày với lịch)
Mong muốn:
Chỉ sinh việc lúc 7h sáng, và date_time_todo  là 8h sáng
