### ISSUE TITLE
[Web] [Lịch sử Tài sản] [Lịch sử Quản lý tài sản- Giao TS] Sai tên cột ' Ngày bắt đầu', Sai hiển thị thông số 'Ngày bắt đầu', Sai thứ tự sắp xếp lịch sử

### ISSUE THREAD

**Issue by tuyennehihi111601** [thanhhuyenle612/Planer#109]
**I. Map ID TestCase**: QLCV_04_02

**II. Mô tả**

Link URL: https://dev01-tfm.tng-holdings.vn/cms/manage/preventive-maintenance

Acc:Nguyễn Thị Tuyến-TNTEC-CSKH

**Điều kiện**
User thao tác Cập nhật CSH tài sản trước đó
**Step**
1. Tại màn hình Danh sách tài sản > Click icon 3 chấm > Chọn Xem 
2. Chọn Tap Lịch sử Quản lý Tài sản

**III. Kết quả thực tế**
- Text 'Ngày yêu cầu'
- Giao cho CSH A từ ngày 21/11 nhưng tại lịch sử lại bị lùi đi 1 ngày là ngày 20/11
- Sắp xếp lịch sử theo thời giao giao đầu tiên đến cuối cùng 
- Không có dữ liệu Ngày kết thúc

**IV. Kết quả mong muốn**
- Text 'Ngày bắt đầu'
- Hiển thị đúng thời gian ' Ngày bắt đầu' giống khi điền popup Cập nhật CSH
- Sắp xếp lịch sử theo Thời gian được giao gần nhất
- Ngày kết thúc của người này = (Ngày bắt đầu -1) Của người ngay sau đó 
![Image](https://github.com/user-attachments/assets/dae40b09-e771-4869-af04-ee2f635ce506)

**Comment by duclv66** [comment]
@luulv2649 nhờ hỗ trợ thêm sort mặc định giảm dần theo trường: memberStartDate
api: https://dev01-tfm-api.tng-holdings.vn/api/v1/assets/get-asset-owner-by-asset-id?id=01JFHD546GK4D8HVPXZ1KY9Z3A&owner-type=1

**Comment by duclv66** [comment]
Thêm data trường memberEndDate: Ngày kết thúc của người này = (Ngày bắt đầu -1) Của người ngay sau đó

**Comment by tuyennehihi111601** [comment]
Chưa sửa
