### ISSUE TITLE
[Web] [Lịch sử kiểm kê] Không hiển thị trạng thái tài sản, Sắp xếp thứ tự kiểm kê không đúng

### ISSUE THREAD

**Issue by tuyennehihi111601** [thanhhuyenle612/Planer#113]
**I. Map ID TestCase**: QLCV_04_02

**II. Mô tả**

Link URL: https://dev01-tfm.tng-holdings.vn/cms/manage/preventive-maintenance

Acc:Nguyễn Thị Tuyến-TNTEC-CSKH

**Điều kiện**
Đã kiểm kê tài sản trước đó
**Step**
1. Thực hiện kiểm kê tài sản 
2. Kiểm tra lưu trữ lịch sử kiểm kê của tài sản

**III. Kết quả thực tế**
- Sắp xếp thứ tự kiểm kê không rõ theo gì ?
- Nếu Khi kiểm kê không thau đổi Trạng thái tài sản > Tại Lịch sử kiểm kê không hiển thị trạng thái tài sản
- Không phân trang > nhiều đợt kiểm kê popup sẽ dài vô tận
**IV. Kết quả mong muốn**
- Sắp xếp lịch sử kiểm kê theo thời gian kiểm kê gần nhất 
- Hiển thị đẩy đủ thông tin Trạng thái tài sản
- Phân trang, giới hạn popup
![Image](https://github.com/user-attachments/assets/f3f97c20-0d10-4362-b987-5f2574cd302f)

**Comment by Linhnv0917** [comment]
Đã phân trang giới hạn chiều cao modal
Assign lại cho BE 2 bug ở trên do BE đang trả về thiếu dữ liệu

**Comment by Linhnv0917** [comment]
Bug 1: hiện tại BE chỉ trả về thông tin theo ngày, không có giờ phút giây nên không thể sort
Bug 2: trường assetStatusName trong inventoryHistories api api/v1/assets/search chưa trả về dữ liệu
=> assign lại BE
