### ISSUE TITLE
[Web] [Lịch sử bảo trì] Sai thông tin các cột và dữ liệu

### ISSUE THREAD

**Issue by tuyennehihi111601** [thanhhuyenle612/Planer#114]
**I. Map ID TestCase**: LOG_BTSC_02

**II. Mô tả**

Link URL: https://dev01-tfm.tng-holdings.vn/cms/manage/preventive-maintenance

Acc:Nguyễn Thị Tuyến-TNTEC-CSKH

**Điều kiện**
Đã thực thi, tạo CVDK, SC
**Step**
1. Tại màn hình Danh sách tài sản > Click icon 3 chấm > Chọn Xem 
2. Chọn Lịch sử Bảo trì&Sửa chữa

**III. Kết quả thực tế**
Các cột dữ liệu gồm:
- Mô tả
- Thời gian thực hiện 
- Thời gian hoàn thành dự kiến
- Thời gian hoàn thành thực tế 
- Người bảo trì
- Mã công việc
- Loại công việc 
![Image](https://github.com/user-attachments/assets/b539492c-9def-4f7e-a0d4-a8ac0905ac84)
**IV. Kết quả mong muốn**
Các cột dữ liệu gồm và sắp xếp theo đúng thứ tự
- Mã công việc : Ticket_code
- Tên công việc: Ticket_name
- Ngày thực hiện: Date_time_todo
- Ngày hoàn thành : Date_time_completed
- Trạng thái: Status
- Người bảo trì : assigned_to

![Image](https://github.com/user-attachments/assets/64d7614a-3d3f-47fd-bd04-6cd12a796150)

**Comment by duclv66** [comment]
@luulv2649 nhờ BE hỗ trợ trả về thêm ticketName, status ở api: 
https://dev01-tfm-api.tng-holdings.vn/api/v1/assets/ticket-history?id=01JFHD546GK4D8HVPXZ1KY9Z3A và các api liên quan tới ticket

**Comment by luulv2649** [comment]
@duclv66 BE done
