### ISSUE TITLE
[Loại sự cố]_Dữ liệu trường Chi nhánh (branch_id) chưa hiển thị trên giao diện

### ISSUE THREAD

**Issue by HueTranKieuAnh** [thanhhuyenle612/Planer#121]
1. Mong muốn
- Sau khi Thêm, sửa Loại sự cố, các dữ liệu đã được nhập ở trường Chi nhánh phải được lưu lại trong db, và hiển thị trên giao diện
2. Thực tế
Khi Thêm, sửa Loại sự cố, các dữ liệu đã được nhập ở trường Chi nhánh chỉ được lưu trong db, chứ không hiển thị trên giao diện. Ảnh minh họa![Image](https://github.com/user-attachments/assets/5fb0c6b3-27dd-40c5-ba7a-ba30c796ae1e)

**Comment by duclv66** [comment]
@luulv2649 nhờ hỗ trợ trả về thêm trường chi nhánh trong api: 
https://dev01-tfm-api.tng-holdings.vn/api/v1/problem-type/search
field: branch: { branchName }
