### ISSUE TITLE
[Web-Tài sản] Bổ sung thêm các trường (site, region, building, floor) trong bảng asset

### ISSUE THREAD

**Issue by HueTranKieuAnh** [thanhhuyenle612/Planer#70]
- Mong muốn: Khi điền thông tin các trường về địa điểm của tài sản (site, region, building, floor, room) trên web, dữ liệu sẽ được lưu trong db
- Thực tế: Khi điền đầy đủ các thông tin về (site, region, building, floor, room) của tài sản trên web nhưng không lưu được vào db
- Nguyên nhân: Do bạn đầu trong bảng asset chỉ lưu trường room_id, sau mới bổ sung các trường khác. Các thông tn hiển thị trên giao diện được lấy theo room_id

**Comment by luulv2649** [comment]
Hôm sau mô tả chính xác vấn đề

**Comment by Linhnv0917** [comment]
FE đã xử lý

**Comment by HueTranKieuAnh** [comment]
Khi vào chỉnh sửa tài sản, các trường dữ liệu về địa điểm của tài sản không còn hiển thị trên màn hình nữa. Nhưng check trong db vẫn có dữ liệu. 
- VD: asset_code = ELV-CC-5
![Image](https://github.com/user-attachments/assets/72f6ca57-7c44-4f2b-a762-a87b2e631f28)
