### ISSUE TITLE
[TÍCH HỢP TSIE-TFM]_dữ liệu đã nhận về db nhưng chưa hiển thị trên web

### ISSUE THREAD

**Issue by HueTranKieuAnh** [thanhhuyenle612/Planer#74]
1. Hoàng
- Dữ liệu trường branch_id sinh ra theo problem_type_id
- Thêm trường ticket.happen_time trong db TFM. happen_time trong TFM= happen_time trong TSI
- id chuyển hết sang dạng chuỗi số sinh tự động, tăng dần, kiểu dữ liệu varchar (32)
- ticket code cần unique, sinh theo quy tắc SC_STT (trong đó STT tăng dần)
- Dữ liệu tích hợp về db cần phải hiển thị được trên giao diện

**Comment by HoangDst** [comment]
t
