### ISSUE TITLE
[Web-Danh mục tài sản]_FE-Chỉnh sửa hiển thị các trường thông tin

### ISSUE THREAD

**Issue by HueTranKieuAnh** [thanhhuyenle612/Planer#85]
- Các trường hiển thị số: có dấu ngăn cách giữa các hàng

- Khi 1 chức năng có nhiều tab => cần phải fix độ rộng của các tab. VD: xem, sửa tài sản

-  Xem TS (màn Lịch sử bảo trì) loại ticket: cần định nghĩa theo Tiếng Việt

- Xem TS (màn Lịch sử sử dụng TS): Ng sở hữu: ngày kết thúc của ng trc bằng ngày bắt đầu của ng sau trừ đi 1 ngày

**Comment by Linhnv0917** [comment]
Issue cuối (Xem TS (màn Lịch sử sử dụng TS): Ng sở hữu: ngày kết thúc của ng trc bằng ngày bắt đầu của ng sau trừ đi 1 ngày) là của BE, BA test và assign lại

**Comment by HueTranKieuAnh** [comment]
- Nội dung số 2 chưa hoàn thành: Khi 1 chức năng có nhiều tab => cần phải fix độ rộng của các tab. VD: xem, sửa tài sản
- Nội dung số 3 chưa xong: ![Image](https://github.com/user-attachments/assets/14bd2e66-b593-4ef3-a7d7-407c3d463f6a)
