### ISSUE TITLE
[Web] Kiểm tra chức năng chọn [Chi nhánh] - Các chi nhánh Off vẫn hiển thị cho phép chọn

### ISSUE THREAD

**Issue by tuyennehihi111601** [thanhhuyenle612/Planer#92]
**I. Map ID TestCase**: CSH_FUN_01_03

**II. Mô tả**

Link URL: https://dev01-tfm.tng-holdings.vn/cms/manage/preventive-maintenance

Acc: Nguyễn Thị Tuyến-TNTEC-CSKH

**Step:**
1. Click textbox [Chi nhánh]
2. Chọn 1 chi nhánh bất kỳ 

**III. Kết quả thực tế**
Các chi nhánh ở trạng thái Off vẫn hiển thị và cho phép chọn

**[IV. Kết quả mong muốn](url)**
Danh sách [Chi nhánh] hiển thị dưới dạng drop list
- Chỉ hiển thị những [Chi nhánh ] đang ở trạng thái ON

![Image](https://github.com/user-attachments/assets/6d5c2993-8e7d-441e-a056-b6b82b23e8a3)

![Image](https://github.com/user-attachments/assets/dd58d6e5-93e3-4f25-9ad4-a1a44b7500d6)

**Comment by Linhnv0917** [comment]
Bug này FE đã xử lý, assign lại cho BE

**Comment by luulv2649** [comment]
Đợi BA confirm

**Comment by HueTranKieuAnh** [comment]
- Đối với phần hiển thị danh sách như ảnh 1: ![Image](https://github.com/user-attachments/assets/f2bce44d-84b0-4d29-8913-1805b251e9e7)
=> Chỉ hiển thị những dòng dữ liệu active. Những dòng inactive => ẩn không hiển thị
- Đối với phần hiển thị ở màn danh sách Cơ cấu tổ chức như ảnh 2 ![Image](https://github.com/user-attachments/assets/d981c5cf-a38c-4b83-91ad-ad57089b9e29)
=> Vẫn hiển thị tất cả danh sách dữ liệu. Tuy nhiên, với các dòng dữ liệu inactive sẽ hiển thị disable
- Khi inactive cha thì tất cả các chi nhánh con đều inactive theo. Sau khi active lại chi nhánh cha thì phải khôi phục lại trạng thái ban đầu của chi nhánh con
**Ví dụ:**: 
  - An ninh GMC đang inactive và BQL GMC active như ảnh ![Image](https://github.com/user-attachments/assets/1410cffe-967f-42c8-b2dd-302de2e855f7)
  - Khi inactive BQL GMC => Cả an ninh GMC và CSKH GMC đều inactive. nhưng khi active lại BQL GMC => an ninh GMC phải khôi phục trạng thái ban đầu là inactive. Tương tự với CSKH GMC
- Khi các dữ liệu đã inactive, không cho phép chỉnh sửa các trường thông tin khác ngoài active. Chỉ được chỉnh sửa sau khi đã active
