### ISSUE TITLE
[Web] [Cập nhật CSH] Kiểm tra cập nhật thông tin Chủ sở hữu -  Ngày bắt đầu sở hữu hiển thị sai so với thời gian chọn khi giao  1 ngày

### ISSUE THREAD

**Issue by tuyennehihi111601** [thanhhuyenle612/Planer#95]
**I. Map ID TestCase**: CSH_FUN_02_01

**II. Mô tả**

Link URL: https://dev01-tfm.tng-holdings.vn/cms/manage/preventive-maintenance

Acc:Nguyễn Thị Tuyến-TNTEC-CSKH

**Điều kiện**
User đã cập nhật CSH trước đó

**Step**
1. Tại màn hình [Danh sách tài sản] 
2. Chọn Tài sản 
3.Chọn [Lịch sử Quản lý tài sản]
4. Quan sát thông tin CSH mới nhất 

**III. Kết quả thực tế**
Ngày bắt đầu sở hữu hiển thị sai so với thời gian chọn khi giao  1 ngày
VD: Giao ngày 23.12 -> Khi xem lịch sử sử dụng Ngày bắt đầu là 22.12

**IV. Kết quả mong muốn**
Thông tin CSH mới nhất trùng với thông tin đã cập nhật CSH trước đó

**Comment by Linhnv0917** [comment]
Anh @duclv66 assign lại bên BE nhé ạ
